/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScrapeItem } from '../models/scrape-item';
export interface ReportResponse {
  error?: string | null;
  items?: Array<ScrapeItem> | null;
}
