/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScrapeItem } from '../models/scrape-item';
export interface ScrapeResponse {
  error?: string | null;
  item?: ScrapeItem;
}
