/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScrapeItem {
  place?: number;
  selector?: string | null;
  stamp?: string;
  url?: string | null;
}
