/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionResponse } from '../../models/session-response';

export interface SessionValidatePost$Plain$Params {
}

export function sessionValidatePost$Plain(http: HttpClient, rootUrl: string, params?: SessionValidatePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionResponse>> {
  const rb = new RequestBuilder(rootUrl, sessionValidatePost$Plain.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionResponse>;
    })
  );
}

sessionValidatePost$Plain.PATH = '/Session/Validate';
