/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportRequest } from '../../models/report-request';
import { ReportResponse } from '../../models/report-response';

export interface ReportReportPost$Params {
      body?: ReportRequest
}

export function reportReportPost(http: HttpClient, rootUrl: string, params?: ReportReportPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportResponse>> {
  const rb = new RequestBuilder(rootUrl, reportReportPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportResponse>;
    })
  );
}

reportReportPost.PATH = '/Report/Report';
